from tkinter import *
root=Tk()
root.geometry("644x700")
root.title("Shivam Saxena Calculator")
def click(event):
    text=event.widget.cget("text")
    print(text)
    if text == "=":
         if scvalue.get().isdigit():
             value= int(scvalue.get())
         else:
             value=eval(screen.get())
         scvalue.set(value)
         screen.update()
    elif text == "C":
        scvalue.set(" ")
        screen.update()
    else:
        scvalue.set(scvalue.get() + text)
        screen.update()
scvalue=StringVar()
screen=Entry(root,textvar=scvalue,font="comicsansms 19 bold")
screen.pack(padx="100",fill=X,pady="6",ipadx="8")
f=Frame(root,relief=SUNKEN,borderwidth=6,padx=12,pady=4,bg="pink")
f.pack()
b1=Button(f,text="9",font="comicsansms 19 bold",padx=7,pady=4)
b1.pack(side="left",padx=7,pady=4)
b1.bind("<Button-1>",click)
b2=Button(f,text="8",font="comicsansms 19 bold",padx=7,pady=4)
b2.pack(side="left",padx=7,pady=4)
b2.bind("<Button-1>",click)
b3=Button(f,text="7",font="comicsansms 19 bold",padx=7,pady=4)
b3.pack(side="left",padx=7,pady=4)
b3.bind("<Button-1>",click)
f=Frame(root,relief=SUNKEN,borderwidth=6,padx=12,pady=4,bg="grey")
f.pack()
b4=Button(f,text="6",font="comicsansms 19 bold",padx=7,pady=4)
b4.pack(side="left",padx=7,pady=4)
b4.bind("<Button-1>",click)
b5=Button(f,text="5",font="comicsansms 19 bold",padx=7,pady=4)
b5.pack(side="left",padx=7,pady=4)
b5.bind("<Button-1>",click)
b6=Button(f,text="4",font="comicsansms 19 bold",padx=7,pady=4)
b6.pack(side="left",padx=7,pady=4)
b6.bind("<Button-1>",click)
f=Frame(root,relief=SUNKEN,borderwidth=6,padx=12,pady=4,bg="Pink")
f.pack()
b7=Button(f,text="3",font="comicsansms 19 bold",padx=7,pady=4)
b7.pack(side="left",padx=7,pady=4)
b7.bind("<Button-1>",click)
b8=Button(f,text="2",font="comicsansms 19 bold",padx=7,pady=4)
b8.pack(side="left",padx=7,pady=4)
b8.bind("<Button-1>",click)
b9=Button(f,text="1",font="comicsansms 19 bold",padx=7,pady=4)
b9.pack(side="left",padx=7,pady=4)
b9.bind("<Button-1>",click)
f=Frame(root,relief=SUNKEN,borderwidth=6,padx=12,pady=4,bg="grey")
f.pack()
b10=Button(f,text="0",font="comicsansms 19 bold",padx=9,pady=4)
b10.pack(side="left",padx=7,pady=4)
b10.bind("<Button-1>",click)
b11=Button(f,text="-",font="comicsansms 19 bold",padx=9,pady=4)
b11.pack(side="left",padx=7,pady=4)
b11.bind("<Button-1>",click)
b12=Button(f,text="*",font="comicsansms 19 bold",padx=9,pady=4)
b12.pack(side="left",padx=7,pady=4)
b12.bind("<Button-1>",click)
f=Frame(root,relief=SUNKEN,borderwidth=6,padx=9,pady=4,bg="pink")
f.pack()
b1=Button(f,text="=",font="comicsansms 19 bold",padx=9,pady=4)
b1.pack(side="left",padx=7,pady=4)
b1.bind("<Button-1>",click)
b2=Button(f,text="+",font="comicsansms 19 bold",padx=9,pady=4)
b2.pack(side="left",padx=7,pady=4)
b2.bind("<Button-1>",click)
b3=Button(f,text="/",font="comicsansms 19 bold",padx=9,pady=4)
b3.pack(side="left",padx=7,pady=4)
b3.bind("<Button-1>",click)
f=Frame(root,relief=SUNKEN,borderwidth=6,padx=12,pady=4,bg="grey")
f.pack()
b1=Button(f,text="C",font="comicsansms 19 bold",padx=4,pady=4)
b1.pack(side="left",padx=7,pady=4)
b1.bind("<Button-1>",click)
b2=Button(f,text="%",font="comicsansms 19 bold",padx=4,pady=4)
b2.pack(side="left",padx=7,pady=4)
b2.bind("<Button-1>",click)
b3=Button(f,text="00",font="comicsansms 19 bold",padx=4,pady=4)
b3.pack(side="left",padx=7,pady=4)
b3.bind("<Button-1>",click)
frame1=Frame(root,borderwidth=6,padx=12,pady=4,bg="black")
frame1.pack(padx=12,pady=3)
label1=Label(frame1,text="Made by Shivam Saxena",padx=12,pady=3,font="comicsansms 19 bold")
label1.pack(side="bottom",padx=12,pady=3)
root.mainloop()
